### ISSUE TITLE
Error reported with Mass Update plugin

### ISSUE THREAD

**Issue by SteveRyan-ASU** [pantheon-systems/terminus-mass-update#1]
Entry: 
`terminus site:list --format=list | terminus site:mass-update:apply`

Result (repeated exactly twice on the screen):
 ```
[notice] Found 89 sites.
 [notice] Fetching the list of available updates for each site...
PHP Fatal error:  Uncaught Error: Call to undefined method Pantheon\Terminus\Models\Site::getUpstreamStatus() in /Users/tfserwin/vendor/pantheon-systems/terminus/src/Commands/Upstream/Updates/UpdatesCommand.php:27
Stack trace:
#0 /Users/tfserwin/vendor/pantheon-systems/terminus/src/Commands/Upstream/Updates/UpdatesCommand.php(42): Pantheon\Terminus\Commands\Upstream\Updates\UpdatesCommand->getUpstreamUpdates(Object(Pantheon\Terminus\Models\Site))
#1 /Users/tfserwin/.terminus/plugins/terminus-mass-update-1.x/src/Commands/MassUpdateCommandBase.php(72): Pantheon\Terminus\Commands\Upstream\Updates\UpdatesCommand->getUpstreamUpdatesLog(Object(Pantheon\Terminus\Models\Site))
#2 /Users/tfserwin/.terminus/plugins/terminus-mass-update-1.x/src/Commands/MassUpdateCommandBase.php(24): Pantheon\TerminusMassUpdate\Commands\MassUpdateCommandBase->getAllUpdates(Array)
#3 /Users/tfserwin/.terminus/plugins/terminus-mass-update-1.x/src/Commands/ApplyCommand.php(31): Pantheon\TerminusMassUpdate\Commands\MassUpdateCommandBase->getAllSitesAndUpdate in /Users/tfserwin/vendor/pantheon-systems/terminus/src/Commands/Upstream/Updates/UpdatesCommand.php on line 27
```

Thanks for the hard work that you guys and gals do to make Pantheon a great experience!

**Comment by SteveRyan-ASU** [comment]
Thanks for fix @ronan. Plugin is working great. :-)

Figured out that I needed to update the plugin by running the curl script from the install instructions again. Wondering if this is the best way? Or, would it be better to `git clone` back from this repo into `~/.terminus/plugins`?
